# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Evan Barger
email: epbarger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Evan Barger, Boston area software developer and electronics hobbyist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://epbarger.github.io" # the base hostname & protocol for your site
github_username:  epbarger
linkedin_username: epbarger
# Build settings
markdown: kramdown
kramdown: 
  parse_block_html: true
